"""World-record lookup: powerlifting, strongman, and grip sport.

Searches a bundled snapshot of world records (see `_records_data.py`,
generated by tools/build_records.py) by sport, lift/event, sex, weight
class (or bodyweight), and equipment - and can express your own lift as a
percentage of the matching record.

Where the numbers come from, and what "record" means here:

    powerlifting - COMPUTED from the OpenPowerlifting project's public-
        domain database of ~4M sanctioned meet results
        (https://www.openpowerlifting.org). Two scopes: "all-time" (heaviest
        successful lift ever recorded in any sanctioned federation) and
        "tested" (same, restricted to drug-tested meets). These are the
        empirical maxima in the data, NOT any single federation's official
        record list - federations (e.g. the IPF at goodlift.info) curate
        their own lists and reset them on rule changes. Weight classes are
        the traditional all-time ones (men 52..140/140+, women 44..110/110+),
        assigned from the lifter's actual bodyweight at the meet; "open" is
        the best across all bodyweights. Equipment follows OpenPowerlifting:
        raw, wraps, single-ply, multi-ply.
    strongman / grip - CURATED. Neither sport has an open database or API,
        so these records are hand-verified against federation pages, event
        organizers (WSM, Giants Live, official implement makers like
        IronMind), and grip-sport record keepers, each entry carrying its
        own citation URL and a confidence grade. Scope is "official" (the
        sanctioning body recognizes it) or "unofficial" (well-documented but
        outside a sanctioning body's list). Most events are contested open-
        weight; a few carry classes like "u90"/"u105" where a body actually
        sanctions them.

The dataset is a snapshot (its date is in `records_as_of()`), bundled so the
tool keeps working offline with no network calls. Records move - treat a
months-old snapshot as "current or recent record", and regenerate via
tools/build_records.py for the latest.

Units: every record carries its own unit - "kg" for lifts, "m" for the keg
toss, "s" for timed holds. Comparisons (`percent_of_record`) only make sense
against kg records and raise ValueError otherwise.
"""

from __future__ import annotations

from dataclasses import dataclass

from liftmath._records_data import DATASET

SPORTS = ("powerlifting", "strongman", "grip")
POWERLIFTING_LIFTS = ("squat", "bench", "deadlift", "total")
EQUIPMENT = ("raw", "wraps", "single-ply", "multi-ply")

# Traditional all-time weight-class ceilings, kg - the same table
# tools/build_records.py assigns classes with (keep the two in sync).
PL_CLASSES = {
    "M": (52.0, 56.0, 60.0, 67.5, 75.0, 82.5, 90.0, 100.0, 110.0, 125.0, 140.0),
    "F": (44.0, 48.0, 52.0, 56.0, 60.0, 67.5, 75.0, 82.5, 90.0, 100.0, 110.0),
}

_SEX_ALIASES = {"m": "M", "male": "M", "f": "F", "female": "F"}


@dataclass
class Record:
    """One world record: what was lifted, by whom, under which rules."""

    sport: str
    lift: str
    lift_display: str
    sex: str
    weight_class: str | None
    equipment: str | None
    scope: str
    value: float
    unit: str
    athlete: str
    date: str
    federation: str | None
    competition: str | None
    country: str | None
    bodyweight_kg: float | None
    source: str | None
    confidence: str | None
    notes: str | None


def records_as_of() -> str:
    """Snapshot date (YYYY-MM-DD) of the bundled dataset."""
    return DATASET["as_of"]


def _canonical_sex(sex: str) -> str:
    canonical = _SEX_ALIASES.get(sex.lower())
    if canonical is None:
        raise ValueError(f"sex must be male/female (or M/F), got {sex!r}")
    return canonical


def weight_class_for(bodyweight_kg: float, sex: str) -> str:
    """Traditional powerlifting weight-class label ("82.5", "140+") for a bodyweight."""
    if bodyweight_kg <= 0:
        raise ValueError("bodyweight_kg must be > 0")
    ceilings = PL_CLASSES[_canonical_sex(sex)]
    for ceiling in ceilings:
        if bodyweight_kg <= ceiling:
            return f"{ceiling:g}"
    return f"{ceilings[-1]:g}+"


def _to_record(raw: dict) -> Record:
    cls = raw["cls"]
    return Record(
        sport=raw["sport"],
        lift=raw["lift"],
        lift_display=raw.get("lift_display") or raw["lift"].capitalize(),
        sex=raw["sex"],
        weight_class=None if cls == "open" else cls,
        equipment=raw.get("equip"),
        scope=raw["scope"],
        value=raw["value"],
        unit=raw["unit"],
        athlete=raw["athlete"],
        date=raw["date"],
        federation=raw.get("fed"),
        competition=raw.get("meet"),
        country=raw.get("country"),
        bodyweight_kg=raw.get("bw"),
        source=raw.get("source"),
        confidence=raw.get("confidence"),
        notes=raw.get("notes"),
    )


def _cls_rank(cls: str | None) -> tuple:
    if cls is None:
        return (2, 0.0, "")  # open last, after the superheavies
    if cls.endswith("+"):
        return (1, float(cls[:-1]), "")
    core = cls[1:] if cls.startswith("u") else cls  # strongman-style "u90"/"u105"
    try:
        return (0, float(core), "")
    except ValueError:
        # Non-weight "classes" (e.g. the CoC gripper ladders) sort last, by label.
        return (3, 0.0, cls)


def search_records(
    sport: str | None = None,
    lift: str | None = None,
    sex: str | None = None,
    weight_class: str | None = None,
    bodyweight_kg: float | None = None,
    equipment: str | None = None,
    scope: str | None = None,
) -> list[Record]:
    """Filter the bundled records; every argument left as None is a wildcard.

    Args:
        sport: "powerlifting", "strongman", or "grip".
        lift: lift/event key - powerlifting's squat/bench/deadlift/total, or
            an event key like "log-lift", "atlas-stone", "two-hands-pinch".
        sex: "male"/"female" (or "M"/"F").
        weight_class: class label to match exactly - "82.5", "140+", "u105",
            or "open" for the across-all-bodyweights record.
        bodyweight_kg: convenience alternative to weight_class - mapped to
            the traditional powerlifting class for the given sex (requires
            sex, powerlifting only; mutually exclusive with weight_class).
        equipment: powerlifting only - raw, wraps, single-ply, multi-ply.
        scope: "all-time"/"tested" (powerlifting), "official"/"unofficial"
            (strongman & grip).

    Returns:
        Matching records, sorted by sport, lift, sex, class, equipment, scope.

    Raises:
        ValueError: on an unknown sport/sex/equipment value, or a
            weight_class + bodyweight_kg combination that conflicts.
    """
    if sport is not None and sport not in SPORTS:
        raise ValueError(f"sport must be one of {SPORTS}, got {sport!r}")
    if equipment is not None and equipment not in EQUIPMENT:
        raise ValueError(f"equipment must be one of {EQUIPMENT}, got {equipment!r}")
    if sex is not None:
        sex = _canonical_sex(sex)
    if bodyweight_kg is not None:
        if weight_class is not None:
            raise ValueError("pass weight_class or bodyweight_kg, not both")
        if sex is None:
            raise ValueError("bodyweight_kg needs sex to resolve a weight class")
        weight_class = weight_class_for(bodyweight_kg, sex)

    matches = []
    for raw in DATASET["records"]:
        if sport is not None and raw["sport"] != sport:
            continue
        if lift is not None and raw["lift"] != lift:
            continue
        if sex is not None and raw["sex"] != sex:
            continue
        if weight_class is not None and raw["cls"] != weight_class:
            continue
        if equipment is not None and raw.get("equip") != equipment:
            continue
        if scope is not None and raw["scope"] != scope:
            continue
        matches.append(_to_record(raw))

    matches.sort(key=lambda r: (r.sport, r.lift, r.sex, _cls_rank(r.weight_class),
                                r.equipment or "", r.scope))
    return matches


def percent_of_record(lift_kg: float, record: Record) -> float:
    """Your lift as a percentage of a (kg-unit) record.

    Raises:
        ValueError: if lift_kg <= 0, or the record isn't weight-based
            (keg-toss meters, timed holds).
    """
    if lift_kg <= 0:
        raise ValueError("lift_kg must be > 0")
    if record.unit != "kg":
        raise ValueError(f"record for {record.lift_display!r} is measured in "
                         f"{record.unit}, not kg - can't compare a weight to it")
    return lift_kg / record.value * 100.0
