"""World-record lookup: powerlifting, strongman, grip sport, and track & field.

Searches a bundled snapshot of records (see `_records_data.py`, generated by
tools/build_records.py) by sport, lift/event, sex, weight class (or
bodyweight), equipment, and - for track & field - level (world / college /
high school), and can express your own lift or mark as a percentage of the
matching record.

Where the numbers come from, and what "record" means here:

    powerlifting - COMPUTED from the OpenPowerlifting project's public-
        domain database of ~4M sanctioned meet results
        (https://www.openpowerlifting.org). Two scopes: "all-time" (heaviest
        successful lift ever recorded in any sanctioned federation) and
        "tested" (same, restricted to drug-tested meets). These are the
        empirical maxima in the data, NOT any single federation's official
        record list - federations (e.g. the IPF at goodlift.info) curate
        their own lists and reset them on rule changes. Weight classes are
        the traditional all-time ones (men 52..140/140+, women 44..110/110+),
        assigned from the lifter's actual bodyweight at the meet; "open" is
        the best across all bodyweights. Equipment follows OpenPowerlifting:
        raw, wraps, single-ply, multi-ply.
    strongman / grip - CURATED. Neither sport has an open database or API,
        so these records are hand-verified against federation pages, event
        organizers (WSM, Giants Live, official implement makers like
        IronMind), and grip-sport record keepers, each entry carrying its
        own citation URL and a confidence grade. Scope is "official" (the
        sanctioning body recognizes it) or "unofficial" (well-documented but
        outside a sanctioning body's list). Most events are contested open-
        weight; a few carry classes like "u90"/"u105" where a body actually
        sanctions them.
    track & field - CURATED, three levels. "world" = World Athletics senior
        outdoor world records; "college" = US collegiate (NCAA) outdoor
        records per the Track & Field News collegiate lists; "high-school" =
        US national high school outdoor records (Track & Field News / NFHS
        convention). Times carry direction="lower" (faster is better) and a
        conventional display string ("1:40.91"); field events are meters,
        combined events points. High-school throws use lighter implements
        than college/world - each such record's notes say so; the levels are
        deliberately NOT cross-comparable.

Weight classes (powerlifting) come in two schemes: "traditional" (the
all-time-record convention: men 52..140/140+, women 44..110/110+) and "ipf"
(the IPF's current senior classes: men 59..120/120+, women 47..84/84+).
Class records exist in both schemes, tagged by `scheme`; the open class is
scheme-neutral.

The dataset is a snapshot (its date is in `records_as_of()`), bundled so the
tool keeps working offline with no network calls. Records move - treat a
months-old snapshot as "current or recent record", and regenerate via
tools/build_records.py for the latest.

Units: every record carries its own unit - "kg" for lifts, "m" for the keg
toss, "s" for timed holds. Comparisons (`percent_of_record`) only make sense
against kg records and raise ValueError otherwise.
"""

from __future__ import annotations

from dataclasses import dataclass

from liftmath._records_data import DATASET

SPORTS = ("powerlifting", "strongman", "grip", "track")
POWERLIFTING_LIFTS = ("squat", "bench", "deadlift", "total")
EQUIPMENT = ("raw", "wraps", "single-ply", "multi-ply")
LEVELS = ("world", "college", "high-school")
SCHEMES = ("traditional", "ipf")

# Weight-class ceilings, kg, per scheme - the same tables
# tools/build_records.py assigns classes with (keep the two in sync).
PL_CLASSES = {
    "traditional": {
        "M": (52.0, 56.0, 60.0, 67.5, 75.0, 82.5, 90.0, 100.0, 110.0, 125.0, 140.0),
        "F": (44.0, 48.0, 52.0, 56.0, 60.0, 67.5, 75.0, 82.5, 90.0, 100.0, 110.0),
    },
    "ipf": {
        "M": (59.0, 66.0, 74.0, 83.0, 93.0, 105.0, 120.0),
        "F": (47.0, 52.0, 57.0, 63.0, 69.0, 76.0, 84.0),
    },
}

_SEX_ALIASES = {"m": "M", "male": "M", "f": "F", "female": "F"}


@dataclass
class Record:
    """One record: what was lifted/run/thrown, by whom, under which rules.

    direction says which way "better" points: "higher" (weights, distances,
    points, timed holds) or "lower" (track times). display is the mark as
    conventionally written where that differs from the bare value (track
    times like "1:40.91"); scheme tags which weight-class table a
    powerlifting class row belongs to; level is track & field's
    world/college/high-school split.
    """

    sport: str
    lift: str
    lift_display: str
    sex: str
    weight_class: str | None
    equipment: str | None
    scope: str
    value: float
    unit: str
    direction: str
    display: str | None
    athlete: str
    date: str
    federation: str | None
    competition: str | None
    country: str | None
    meet_country: str | None
    bodyweight_kg: float | None
    level: str | None
    scheme: str | None
    dots: float | None
    goodlift: float | None
    source: str | None
    confidence: str | None
    notes: str | None


def records_as_of() -> str:
    """Snapshot date (YYYY-MM-DD) of the bundled dataset."""
    return DATASET["as_of"]


def _canonical_sex(sex: str) -> str:
    canonical = _SEX_ALIASES.get(sex.lower())
    if canonical is None:
        raise ValueError(f"sex must be male/female (or M/F), got {sex!r}")
    return canonical


def weight_class_for(bodyweight_kg: float, sex: str, scheme: str = "traditional") -> str:
    """Powerlifting weight-class label ("82.5", "140+") for a bodyweight.

    scheme picks the class table: "traditional" (all-time convention) or
    "ipf" (current IPF senior classes).
    """
    if bodyweight_kg <= 0:
        raise ValueError("bodyweight_kg must be > 0")
    if scheme not in SCHEMES:
        raise ValueError(f"scheme must be one of {SCHEMES}, got {scheme!r}")
    ceilings = PL_CLASSES[scheme][_canonical_sex(sex)]
    for ceiling in ceilings:
        if bodyweight_kg <= ceiling:
            return f"{ceiling:g}"
    return f"{ceilings[-1]:g}+"


def parse_mark(text: str) -> float:
    """Parse a track-style mark into seconds (or a plain number for field marks).

    Accepts "9.58", "1:40.91" (M:SS), and "2:00:35" (H:MM:SS); a trailing
    "s" is tolerated. Plain numbers pass through, so the same parser reads
    a 5000m time and a shot-put distance.
    """
    cleaned = text.strip().rstrip("s")
    if not cleaned:
        raise ValueError("empty mark")
    parts = cleaned.split(":")
    if len(parts) > 3:
        raise ValueError(f"can't parse mark {text!r}")
    total = 0.0
    for part in parts:
        value = float(part)  # raises ValueError on junk, which is the right error
        if value < 0:
            raise ValueError("mark parts must be >= 0")
        total = total * 60.0 + value
    return total


def format_seconds(seconds: float) -> str:
    """Format seconds the way track marks are written: 9.58, 1:40.91, 2:00:35.

    Under a minute keeps two decimals; minutes keep two decimals on the
    seconds; hours drop to whole seconds (marathon convention).
    """
    if seconds < 0:
        raise ValueError("seconds must be >= 0")
    # Round to display precision before picking a bucket, not after - a raw
    # value within half a unit of a boundary (59.999, 3599.996) otherwise
    # slips into the lower bucket and then rounds up during formatting,
    # printing an invalid "60.00" or "59:60.00" instead of crossing over.
    rounded = round(seconds, 2)
    if rounded < 60:
        return f"{rounded:.2f}"
    if rounded < 3600:
        minutes, rest = divmod(rounded, 60)
        return f"{int(minutes)}:{rest:05.2f}"
    hours, rest = divmod(round(seconds), 3600)
    minutes, whole = divmod(rest, 60)
    return f"{int(hours)}:{int(minutes):02d}:{int(whole):02d}"


def _to_record(raw: dict) -> Record:
    cls = raw["cls"]
    return Record(
        sport=raw["sport"],
        lift=raw["lift"],
        lift_display=raw.get("lift_display") or raw["lift"].capitalize(),
        sex=raw["sex"],
        weight_class=None if cls == "open" else cls,
        equipment=raw.get("equip"),
        scope=raw["scope"],
        value=raw["value"],
        unit=raw["unit"],
        direction=raw.get("direction") or "higher",
        display=raw.get("display"),
        athlete=raw["athlete"],
        date=raw["date"],
        federation=raw.get("fed"),
        competition=raw.get("meet"),
        country=raw.get("country"),
        meet_country=raw.get("meet_country"),
        bodyweight_kg=raw.get("bw"),
        level=raw.get("level"),
        scheme=raw.get("scheme"),
        dots=raw.get("dots"),
        goodlift=raw.get("goodlift"),
        source=raw.get("source"),
        confidence=raw.get("confidence"),
        notes=raw.get("notes"),
    )


def _cls_rank(cls: str | None) -> tuple:
    if cls is None:
        return (2, 0.0, "")  # open last, after the superheavies
    if cls.endswith("+"):
        return (1, float(cls[:-1]), "")
    core = cls[1:] if cls.startswith("u") else cls  # strongman-style "u90"/"u105"
    try:
        return (0, float(core), "")
    except ValueError:
        # Non-weight "classes" (e.g. the CoC gripper ladders) sort last, by label.
        return (3, 0.0, cls)


def search_records(
    sport: str | None = None,
    lift: str | None = None,
    sex: str | None = None,
    weight_class: str | None = None,
    bodyweight_kg: float | None = None,
    equipment: str | None = None,
    scope: str | None = None,
    level: str | None = None,
    scheme: str | None = None,
) -> list[Record]:
    """Filter the bundled records; every argument left as None is a wildcard.

    Args:
        sport: "powerlifting", "strongman", "grip", or "track".
        lift: lift/event key - powerlifting's squat/bench/deadlift/total, or
            an event key like "log-lift", "two-hands-pinch", "100m",
            "pole-vault".
        sex: "male"/"female" (or "M"/"F").
        weight_class: class label to match exactly - "82.5", "140+", "u105",
            or "open" for the across-all-bodyweights record.
        bodyweight_kg: convenience alternative to weight_class - mapped to
            the powerlifting class for the given sex under `scheme`
            (requires sex; mutually exclusive with weight_class).
        equipment: powerlifting only - raw, wraps, single-ply, multi-ply.
        scope: "all-time"/"tested" (powerlifting), "official"/"unofficial"
            (curated sports; track ratifications pending show "pending").
        level: track & field only - "world", "college", "high-school".
        scheme: powerlifting class scheme filter, "traditional" or "ipf".
            Open-class rows are scheme-neutral and match either. Also picks
            the table bodyweight_kg resolves against (default traditional).

    Returns:
        Matching records, sorted by sport, lift, sex, level, class,
        equipment, scope.

    Raises:
        ValueError: on an unknown sport/sex/equipment/level/scheme value, or
            a weight_class + bodyweight_kg combination that conflicts.
    """
    if sport is not None and sport not in SPORTS:
        raise ValueError(f"sport must be one of {SPORTS}, got {sport!r}")
    if equipment is not None and equipment not in EQUIPMENT:
        raise ValueError(f"equipment must be one of {EQUIPMENT}, got {equipment!r}")
    if level is not None and level not in LEVELS:
        raise ValueError(f"level must be one of {LEVELS}, got {level!r}")
    if scheme is not None and scheme not in SCHEMES:
        raise ValueError(f"scheme must be one of {SCHEMES}, got {scheme!r}")
    if sex is not None:
        sex = _canonical_sex(sex)
    if bodyweight_kg is not None:
        if weight_class is not None:
            raise ValueError("pass weight_class or bodyweight_kg, not both")
        if sex is None:
            raise ValueError("bodyweight_kg needs sex to resolve a weight class")
        weight_class = weight_class_for(bodyweight_kg, sex, scheme or "traditional")

    matches = []
    for raw in DATASET["records"]:
        if sport is not None and raw["sport"] != sport:
            continue
        if lift is not None and raw["lift"] != lift:
            continue
        if sex is not None and raw["sex"] != sex:
            continue
        if weight_class is not None and raw["cls"] != weight_class:
            continue
        if equipment is not None and raw.get("equip") != equipment:
            continue
        if scope is not None and raw["scope"] != scope:
            continue
        if level is not None and raw.get("level") != level:
            continue
        # Scheme filters class rows only; the open class belongs to both.
        if scheme is not None and raw.get("scheme") not in (None, scheme):
            continue
        matches.append(_to_record(raw))

    matches.sort(key=lambda r: (r.sport, r.lift, r.sex, r.level or "",
                                _cls_rank(r.weight_class), r.scheme or "",
                                r.equipment or "", r.scope))
    return matches


def percent_of_record(value: float, record: Record) -> float:
    """Your lift/mark as a percentage of a record, direction-aware.

    For "higher"-is-better records (weights, distances, points, timed
    holds) this is value/record; for "lower"-is-better track times it
    inverts to record/value, so 100% always means record-equalling and
    bigger is always better. Pass the value in the record's own unit
    (kg, meters, seconds - `parse_mark` turns "4:12.31" into seconds).

    Raises:
        ValueError: if value <= 0.
    """
    if value <= 0:
        raise ValueError("value must be > 0")
    if record.direction == "lower":
        return record.value / value * 100.0
    return value / record.value * 100.0
